import {
  encode,
} from 'gpt-tokenizer/esm/model/gpt-4-0314'

export const wikipedia = `
Bouvet was a pre-dreadnought battleship of the French Navy that was built in the 1890s. She was a member of a group of five broadly similar battleships, along with Charles Martel, Jauréguiberry, Carnot, and Masséna, which were ordered in response to the British Royal Sovereign class. Bouvet was the last vessel of the group to be built, and her design was based on that of Charles Martel. Like her half-sisters, she was armed with a main battery of two 305 mm (12 in) guns and two 274 mm (10.8 in) guns in individual turrets. She had a top speed of 18 knots (33 km/h; 21 mph), which made her one of the fastest battleships in the world at the time. Bouvet proved to be the most successful design of the five, and she was used as the basis for the subsequent Charlemagne class. Nevertheless, she suffered from design flaws that reduced her stability and contributed to her loss in 1915.

Bouvet spent the majority of her peacetime career in the Mediterranean Squadron conducting routine training exercises. This period was relatively uneventful, though she was involved in a collision with the battleship Gaulois in 1903 that saw both ships' captains relieved of command. In 1906, she assisted in the response to the eruption of Mount Vesuvius in Italy. Bouvet was withdrawn from front-line service in 1907 and thereafter used as part of the training fleet. The ship was the only vessel of her group of five half-sisters still in service at the outbreak of World War I in July 1914.

A significant portion of the French Army was stationed in French North Africa, so at the start of the war, Bouvet and much of the rest of the fleet were used to escort troop convoys across to southern France. With this work done by late August, Bouvet and several other battleships were used to patrol for contraband shipments in the central Mediterranean. From November to late December, she was stationed as a guard ship at the northern entrance to the Suez Canal. The ship thereafter joined the naval operations off the Dardanelles, where she participated in a series of attacks on the Ottoman fortifications guarding the straits. These culminated in a major assault on 18 March 1915; during the attack, she was hit approximately eight times by shellfire but was not seriously damaged. While turning to withdraw, she struck a mine and sank within two minutes; only 75 men were rescued from a complement of 718. Two British battleships were also sunk by mines that day, and the disaster convinced the Allies to abandon the naval campaign in favor of an amphibious assault on the Gallipoli Peninsula.

Design

Illustration of Charles Martel, which formed the basis for Bouvet's design
In 1889, the British Parliament passed the Naval Defence Act that resulted in the construction of the eight Royal Sovereign-class battleships; this major expansion of naval power led the French government to pass its reply, the Statut Naval (Naval Law) of 1890. The law called for a total of twenty-four "cuirasses d'escadre" (squadron battleships) and a host of other vessels, including coastal defense battleships, cruisers, and torpedo boats. The first stage of the program was to be a group of four squadron battleships that were built to different designs but met the same basic characteristics, including armor, armament, and displacement. The naval high command issued the basic requirements on 24 December 1889; displacement would not exceed 14,000 metric tons (14,000 long tons), the primary armament was to consist of 340-millimeter (13 in) and 270 mm (11 in) guns, the belt armor should be 450 mm (17.7 in) thick, and the ships should maintain a top speed of 17 knots (31 km/h; 20 mph). The secondary battery was to be either 140 mm (5.5 in) or 160 mm (6.3 in) caliber, with as many guns fitted as space would allow.[1] The general similarity of the ships led some observers to group them together as a ship class, though the authors of Conway's All the World's Fighting Ships point out that the vessels had "sufficient differences to prevent them from being considered as one class."[2]

The basic design for the ships was based on the previous battleship Brennus, but instead of mounting the main battery all on the centerline, the ships used the lozenge arrangement of the earlier vessel Magenta, which moved two of the main battery guns to single turrets on the wings.[3] Although the navy had stipulated that displacement could be up to 14,000 t, political considerations, namely parliamentary objections to increases in naval expenditures, led the designers to limit displacement to around 12,000 t (12,000 long tons). Five naval architects submitted proposals to the competition; Charles Ernest Huin prepared the design for Bouvet. He had also designed her half-sister Charles Martel, upon which the design for Bouvet was based. Before work on Charles Martel had begun, the naval command asked Huin to design an improved version. He completed the plans for the ship, which was slightly larger than her half-sisters, on 20 May, and the Navy awarded the contract for the ship on 8 October 1892.[4]

Bouvet proved to be the most successful of the five ships, and she was the only one still in active service at the outbreak of World War I. She also provided the basis for the next class of French battleships, the three Charlemagnes built in the mid-1890s. She and her half-sisters nevertheless were disappointments in service; Bouvet suffered from stability problems that ultimately contributed to her loss in 1915, and all five of the vessels compared poorly to their British counterparts, particularly their contemporaries of the Majestic class. The ships suffered from a lack of uniformity of equipment, which made them hard to maintain in service, and their mixed gun batteries comprising several calibers made gunnery in combat conditions difficult, since shell splashes were hard to differentiate. Many of the problems that plagued the ships in service were a result of the limitation on their displacement, particularly their stability and seakeeping.[5]

General characteristics and machinery

Bouvet early in her career
Bouvet was 117.9 meters (386 ft 10 in) long between perpendiculars, 121.01 m (397 ft) long at the waterline, and 122.4 m (401 ft 7 in) long overall. She had a beam of 21.4 m (70 ft 3 in) and an average draft of 8 m (26 ft 3 in). She had a displacement of 12,200 t (12,007 long tons) as designed. Unlike her half-sisters, which had a cut down quarterdeck, Bouvet retained a full flush deck. Her superstructure was reduced in size compared to her half-sisters, and she had a pair of short military masts; these changes were made to reduce the top-heaviness experienced with the earlier vessels. She kept the pronounced tumblehome to give the 27 cm guns wide fields of fire. Bouvet had a standard crew of 31 officers and 591 enlisted men, though as a flagship her crew grew to 41 officers and 651 enlisted men.[6]

She had three vertical triple-expansion steam engines each driving a single three-bladed screw; the outboard screws were 4.5 m (15 ft) wide, while the center shaft was slightly smaller, at 4.4 m (14 ft) in diameter. The engines were powered with steam supplied by thirty-two Belleville water-tube boilers that were license-built by Indret. The boilers were divided into four boiler rooms, which were placed in two pairs on either end of the magazines for the wing turrets, and divided by a central bulkhead. The boilers were ducted into a pair of funnels. Her three engines were placed side by side and also divided by longitudinal bulkheads.[7]

Her propulsion system was rated at 14,000 metric horsepower (14,000 ihp), which allowed the ship to steam at a maximum speed of 18 knots (33 km/h; 21 mph) on speed trials with a light loading, though while on a 24-hour test using normal displacement, she cruised at 17 to 17.5 knots (31.5 to 32.4 km/h; 19.6 to 20.1 mph). Using forced draft, she reached 18.2 knots (33.7 km/h; 20.9 mph) from 15,462 metric horsepower (15,250 ihp) during the tests. Bouvet was fast by the standards of the day; the only British battleship that approached her in speed was the second-class battleship HMS Renown. As built, Bouvet could carry 610 t (600 long tons) of coal, though additional space allowed for up to 980 t (960 long tons) in total. At a cruising speed of 9 knots (17 km/h; 10 mph), the ship could steam for 3,000 nautical miles (5,600 km; 3,500 mi).[7][8][9]

The ship's electrical system consisted of four 400-ampere/80-volt dynamos that had a combined output of 128 kilowatts (172 hp). The dynamos were placed on the platform deck between the ducting for the boilers. Several smaller electric motors, rated at 29 kW (39 hp), powered the ship's ventilation system, and 9 kW (12 hp) motors drove the ash hoists for the boiler rooms. Bouvet was fitted with six searchlights: four on the battery deck (two amidships and one each forward and aft) and the remaining two on the masts.[7]

Armament

Bouvet at anchor, c. June 1912
Bouvet's main armament consisted of two Canon de 305 mm Modèle 1893 guns in two single-gun turrets, one each fore and aft and two Canon de 274 mm Modèle 1893 guns in two single-gun turrets, one amidships on each side, sponsoned out over the tumblehome of the ship's sides.[8] Both types of guns were experimental 45 caliber variants of the guns fitted in her half-sister Masséna. The 305 mm guns had a muzzle velocity of 815 meters per second (2,670 ft/s), which allowed the shells to penetrate up to 610 mm (24 in) of iron armor at a range of 1,800 m (2,000 yd). This was sufficiently powerful to allow Bouvet's main guns to easily penetrate the armor of most contemporary battleships at the common battle ranges of the day. The 274 mm guns, which were also 45 calibers long, had the same muzzle velocity, but being significantly smaller than the 305 mm guns, produced 460 mm (18 in) of iron penetration. The gun turrets were hydraulically operated and required the guns to be depressed to −4° to be loaded. They both had a rate of fire of one shell per minute. Both types of mounts allowed elevation to 14°; for the 305 mm guns, this produced a maximum range of 12,400 m (40,700 ft), and for the 274 mm guns, their maximum range was 11,700 m (38,400 ft).[10][11]

Her secondary armament consisted of eight Canon de 138 mm Modèle 1891 naval guns, which were mounted in single turrets in the hull; two were placed just aft of the forward 305 mm turret, four were placed on either sides of the 274 mm guns, and the remaining two were just aft of the rear 305 mm turret.[8] These guns had a firing rate of 4 rounds per minute, with a maximum range of 11,000 m (36,000 ft) from up to 20° elevation.[10] For defense against torpedo boats, Bouvet carried eight 100 mm (3.9 in) quick-firing (QF) guns in individual pedestal mounts with gun shields on the upper deck. Four were located between the funnels, two were placed abreast of the forward bridge, and the remaining two were similarly arranged on either side of the aft bridge. They had a rate of fire of between 7 and 15 shots per minute and they could engage targets out to 5,000 m (16,000 ft). She also had twelve 47 mm (1.9 in) 3-pounder guns, and eight 37 mm (1.5 in) 1-pounder guns, all in individual mounts. Of the 37 mm guns, three were five-barreled Hotchkiss revolver cannon and the remaining five were single-barrel QF guns. Four of the 47 mm guns were mounted on the lower platforms of the military masts and the remainder, along with the 37 mm guns, were distributed along the length of the superstructure.[12][13]

As was customary for capital ships of the period, her armament suite was rounded out by four 450 mm (18 in) torpedo tubes, two of which were submerged in the ship's hull; both were located on the broadside close to the bow; they were aimed directly perpendicular to the centerline. The other two tubes were mounted above water, in trainable launchers placed amidships. The fire of these tubes was directed either by armored sights located abreast of the conning tower or unprotected sights on the battery deck. Bouvet carried a total of ten torpedoes of the Modèle 1892 Toulon/Fiume type; six were allocated to the submerged tubes, with the other four for the deck launchers. Bouvet also carried twenty Modèle 1892 naval mines that could be laid by the ship's pinnaces.[14]

Fire control
In the early 1890s, before Bouvet had begun construction, the French Navy introduced a fire-control system that included rangefinders, observers in the masts, and electric order transmitters to communicate fire control instructions from the control center to the gun crews. Bouvet was the first battleship completed with the system; for the purposes of fire control, her gun battery was divided into either individual sections (the large and medium-caliber guns) or groups of two or more guns (the 100 mm, 47 mm, and 37 mm guns). All of the guns were controlled by the Poste central de commande (central command post) that was located directly below the conning tower, below the armored deck. The central command post received the range and bearing information from the rangefinders and calculated firing solutions, which would then be sent via the electric order transmitters to direct the fire of individual guns or sections.[15]

Armor

Plan and profile drawing of Bouvet
The ship's armor was constructed with nickel steel manufactured by several firms, including Schneider-Creusot, Saint-Chamond, and Châtillon & Commentry, which allowed the design staff to reduce the thickness of the steel without compromising its effectiveness. Thus, weight could be saved that could be used elsewhere in the displacement-limited ships. The main belt was 400 mm (16 in) thick amidships, and tapered down to 200 mm (7.9 in) at the lower edge. Forward of the central citadel, the belt was reduced to 300 mm (12 in) (also reduced to 200 mm on the lower edge) and aft of the citadel, it tapered to 260 mm (10 in) (reduced to 120 mm (4.7 in) on the bottom edge). The belt extended for the entire length of the hull, and it was backed with 200 mm of teak. Above the belt was 80 mm (3.1 in) thick strake of side armor that created a highly subdivided cofferdam to reduce the risk of flooding from battle damage. The side of the cofferdam was reinforced by two layers of 10 mm (0.39 in) plating. Bouvet's main deck was protected with 70 mm (2.8 in) of mild steel, back with two layers of 10 mm plating. Mild steel was used here, as the deck was designed to bend rather than shatter when struck by an armor-piercing shell at an oblique angle. The lower platform deck was 30 mm (1.2 in) thick, with a single layer of 10 mm plating behind it; it was intended to catch splinters that penetrated the main deck.[16]

The main battery guns (both the 305 mm and 274 mm guns) were protected with 370 mm (15 in) of cemented armor on the faces and sides, with 70 mm (2.8 in) thick roofs and 65 mm (2.6 in) thick floors. Both the floors and roofs were composed of mild steel. The turrets sat atop barbettes with 310 mm (12 in) thick sides. The 138 mm turrets had 100 mm (3.9 in) thick sides and faces, with 20 mm (0.79 in) roofs and 15 mm (0.59 in) floors. Gun shields that were 72 mm (2.8 in) thick protected the 100 mm guns. The conning tower had 320 mm (13 in) thick sides, a 20 mm thick roof, and a 25 mm (0.98 in) thick floor. The uptakes for the boilers were protected with coamings that were 300 mm thick.[16]

The ship's armor layout was not as effective as the designers had hoped; at the designed displacement, the belt armor was submerged with just a 3° heel, and training all of the main battery turrets to one side would produce a heel of 2°. Incremental increases in weight during the construction process, which Huin was unable to supervise, left little margin for the belt to remain above the water. These increases forced compromises elsewhere in the ship's armor protection, most notably the barbettes, which were criticized at the time; nothing could be done, however, due to the strict limit placed on displacement. The cofferdam also proved to be highly susceptible to uncontrollable flooding, which would have serious effects on the vessel's stability.[17]

Service history

Map of the western Mediterranean, where Bouvet spent the majority of her peacetime career
Bouvet was laid down at the French Navy shipyard in Lorient on 16 January 1893, and was launched on 27 April 1896. After completing fitting-out work, she began sea trials on 5 March 1898. The ship was intended to have conducted her trials from Brest, but she was sent to Toulon to reinforce the Mediterranean Squadron due to the Fashoda crisis with Britain. She was commissioned into the French Navy in June 1898.[8][18] The ship was named in honor of Admiral François Joseph Bouvet.[19]

Throughout the ship's peacetime career, she was occupied with routine training exercises that included gunnery training, combined maneuvers with torpedo boats and submarines, and practicing attacking coastal fortifications. Since Bouvet was one of the most modern French battleships in the late 1890s and early 1900s, she spent this time in the Mediterranean Squadron, France's primary fleet. One of the largest of these exercises was conducted between March and July 1900, and involved the Mediterranean Squadron and the Northern Squadron. On 6 March, Bouvet joined the battleships Brennus, Gaulois, Charlemagne, Charles Martel, and Jauréguiberry and four protected cruisers for maneuvers off Golfe-Juan on the Côte d'Azur, including night firing training. Over the course of April, the ships visited numerous French ports along the Mediterranean coast, and on 31 May the fleet steamed to Corsica for a visit that lasted until 8 June. After completing its own exercises in the Mediterranean, the Mediterranean Squadron rendezvoused with the Northern Squadron off Lisbon, Portugal, in late June before proceeding to Quiberon Bay for joint maneuvers in July. The maneuvers concluded with a naval review in Cherbourg on 19 July for President Émile Loubet. On 1 August, the Mediterranean Fleet departed for Toulon, arriving on 14 August.[20]

Bouvet was assigned to the 2nd Battle Division of the Mediterranean Squadron, along with Jauréguiberry and the new battleship Iéna, the latter becoming the divisional flagship. Bouvet departed Toulon on 29 January 1903 in company with the battleships Saint Louis, Gaulois, and Charlemagne, four cruisers, and accompanying destroyers for gunnery training off Golfe-Juan. At the time, Bouvet and Gaulois were the 2nd Division, with Bouvet in the lead; the other two ships formed the 1st Division. Two days later, when the divisions were ordered to change from two columns to a single line ahead for shooting drills, Bouvet failed to take her prescribed position and instead turned too closely to Gaulois. The latter accidentally struck the former, with Bouvet losing a ladder and incurring damage to one of the deck-mounted torpedo tubes. Gaulois had two armor plates torn from her bow. Both ships' captains were relieved of command over the incident. In October, Bouvet and the rest of the Mediterranean Squadron battleships steamed to Palma de Mallorca, and on their return to Toulon they conducted training exercises.[21]

The year 1904 saw the Mediterranean Squadron visit Souda Bay in Crete, Beirut, Smyrna, and Salonika in the Ottoman Empire, Messina in Sicily, and Piraeus, Greece, during a cruise of the eastern Mediterranean in the middle of the year. The following year passed uneventfully for Bouvet, and on 10 April 1906, she, Iéna, and Gaulois were sent to Italy in the aftermath of the eruption of Mount Vesuvius. The three ships carried some 9,000 rations and their crews assisted the victims to recover from the disaster. The division returned to France in time for a naval review on 16 September held in Marseilles that included detachments from Britain, Spain, and Italy. Bouvet and the other French ships then returned to Toulon. The following year, in January 1907, Bouvet was withdrawn from front-line service with the Mediterranean Squadron.[22] Now part of the Second Squadron, she was retained on active service for the year, but with a reduced crew.[23] In July 1908, the Mediterranean Fleet was reorganized and Bouvet was attached to the 3rd Battleship Division as its flagship, under the command of Contre-amiral (Rear Admiral) Laurent Marin-Darbel, along with Jauréguiberry and the battleship Suffren.[24]


Bouvet in the Dardanelles in 1915
Beginning in January 1909, with the commissioning of the six République and Liberté-class battleships, the Mediterranean Squadron was reorganized into two battle squadrons; Bouvet was at that time assigned to the 3rd Division, part of the 2nd Battle Squadron, still the flagship of Marin-Darbel. Her place was taken the following year by Saint Louis, and she remained out of service that year, with the exception of during the fleet maneuvers conducted in June, which she joined. In January 1911, she returned to service as the flagship of Contre-amiral Adam in the 2nd Division of the 2nd Battle Squadron. On 5 October, the fleet was again reorganized and her place in what was now the 3rd Battle Squadron was taken by Charles Martel. On 16 October 1912, Bouvet, Gaulois, Saint Louis, Carnot, Masséna, and Jauréguiberry were activated for training duties as the 3rd Squadron of the Mediterranean Squadron; in July 1913, they were joined by Charlemagne. The squadron was dissolved on 11 November, and Bouvet, Saint Louis, and Gaulois were assigned to the Division de complément (Supplementary Division). Training activities continued into 1914, and in March, the division joined the rest of the Mediterranean Squadron, which was now re-designated as the 1re Armée Navale (First Naval Army) for gunnery training off Corsica. Additional maneuvers were conducted beginning on 13 May, during which the fleet visited Bizerte in French Tunisia, Algiers in French Algeria, and Ajaccio, Corsica.[25]
`.trim()

export const selectTokenAmount = (numberOfTokens: number) => {
  const lines = wikipedia.split("\n")
  const returnedLines = [lines[0]]
  while (encode(returnedLines.join("\n")).length < numberOfTokens) {
    returnedLines.push(lines[returnedLines.length])
  }
  return returnedLines.join("\n")
}